version: "3.7"
services:
  app:
    build:
      args:
        user: runner
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: botolye15
    container_name: botolye15_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - botolye15

  db:
    image: mysql:5.7
    container_name: botolye15_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - botolye15

  nginx:
    image: nginx:alpine
    container_name: botolye15_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - botolye15

networks:
  botolye15:
    driver: bridge
